version: "3.8"
services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  producer:
    build:
      context: ./producer
    container_name: producer
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      NAVER_CLIENT_ID: "${NAVER_CLIENT_ID}"
      NAVER_CLIENT_SECRET: "${NAVER_CLIENT_SECRET}"
      NAVER_LOCATION_SEARCH_URL: "${NAVER_LOCATION_SEARCH_URL:https://openapi.naver.com/v1/search/local.json}"
    depends_on:
      - redis

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    env_file:
      - .env
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      NAVER_CLIENT_ID: "${NAVER_CLIENT_ID}"
      NAVER_CLIENT_SECRET: "${NAVER_CLIENT_SECRET}"
      NAVER_LOCATION_SEARCH_URL: "${NAVER_LOCATION_SEARCH_URL:https://openapi.naver.com/v1/search/local.json}"
    depends_on:
      - redis