name: CD with Gradle and Docker for Producer and Consumer

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - uses: actions/checkout@v4

      # JDK 설정
      - name: ☕️ Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Producer 빌드
      - name: 🐘 Build Producer with Gradle
        working-directory: ./producer
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # Consumer 빌드
      - name: 🐘 Build Consumer with Gradle
        working-directory: ./consumer
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      # Docker 빌드 및 푸시 - Producer
      - name: 💣 Build and Push Producer Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f ./producer/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/roomie-producer:latest ./producer
          docker push ${{ secrets.DOCKER_USERNAME }}/roomie-producer:latest

      # Docker 빌드 및 푸시 - Consumer
      - name: 💣 Build and Push Consumer Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f ./consumer/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/roomie-consumer:latest ./consumer
          docker push ${{ secrets.DOCKER_USERNAME }}/roomie-consumer:latest

      # EC2로 배포
      - name: 🚀 Deploy Producer and Consumer to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "✋ Stopping existing containers"
            sudo docker stop producer || true
            sudo docker stop consumer || true
            sudo docker rm producer || true
            sudo docker rm consumer || true

            echo "🥳 Pulling new Docker images"
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/roomie-producer:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/roomie-consumer:latest

            echo "🌱 Running Producer container"
            sudo docker run -d -p 8080:8080 --name producer \
              -e SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              -e NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
              -e NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
              -e NAVER_LOCATION_SEARCH_URL=${{ secrets.NAVER_LOCATION_SEARCH_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/roomie-producer:latest

            echo "🌱 Running Consumer container"
            sudo docker run -d -p 8081:8080 --name consumer \
              -e SPRING_DATASOURCE_DRIVER_CLASS_NAME=${{ secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
              -e NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }} \
              -e NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }} \
              -e NAVER_LOCATION_SEARCH_URL=${{ secrets.NAVER_LOCATION_SEARCH_URL }} \
              ${{ secrets.DOCKER_USERNAME }}/roomie-consumer:latest

            echo "🚽 Cleaning up unused Docker images"
            sudo docker image prune -f